package Day18;

import java.util.Scanner;

public class ExceptionHandlingProgram {

	public static void main(String[] args)
	{
		
		System.out.println("Program Is Started....");
		/*
.....................Uncheck Exception................................
..........(1) Arithmatic Exception....................................
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter The Number...");
		int num=sc.nextInt();
		try
		{
		
		System.out.println(100/num);
		}
		catch(Exception e)
		{
	     System.out.println(e.getMessage());
		}
		*/
		
/*...................Array Index Out Of Bounds Exception...............*/
	
	/*
	try
	{
		int [] A= new int[5];
	
	    int value=100;
	    int pos=4;
	
	    A[pos]=value;
	    System.out.println(A[pos]);
	}
	catch (Exception e)
	{
		System.out.println(e.getMessage());
	}
	*/
		
		System.out.println("Program Is Ended..");
	
		
	}

}
